<?php

/**
 * BaseCroPages
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $page_url
 * @property string $description
 * @property Doctrine_Collection $CroCms
 * 
 * @method string              getPageUrl()     Returns the current record's "page_url" value
 * @method string              getDescription() Returns the current record's "description" value
 * @method Doctrine_Collection getCroCms()      Returns the current record's "CroCms" collection
 * @method CroPages            setPageUrl()     Sets the current record's "page_url" value
 * @method CroPages            setDescription() Sets the current record's "description" value
 * @method CroPages            setCroCms()      Sets the current record's "CroCms" collection
 * 
 * @package    courtreservationonline
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCroPages extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cro_pages');
        $this->hasColumn('page_url', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('CroCms', array(
             'local' => 'id',
             'foreign' => 'page_url_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}