<?php

/**
 * BaseCroGroups
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $CroAdminUsers
 * 
 * @method string              getName()          Returns the current record's "name" value
 * @method Doctrine_Collection getCroAdminUsers() Returns the current record's "CroAdminUsers" collection
 * @method CroGroups           setName()          Sets the current record's "name" value
 * @method CroGroups           setCroAdminUsers() Sets the current record's "CroAdminUsers" collection
 * 
 * @package    courtreservationonline
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCroGroups extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cro_groups');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('CroAdminUsers', array(
             'local' => 'id',
             'foreign' => 'user_group'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}