<?php

/**
 * BaseCroCms
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $page_url_id
 * @property string $content_name
 * @property string $content_text
 * @property string $content_image
 * @property integer $created_by
 * @property integer $updated_by
 * @property CroAdminUsers $CroAdminUsers
 * @property CroPages $CroPages
 * 
 * @method integer       getPageUrlId()     Returns the current record's "page_url_id" value
 * @method string        getContentName()   Returns the current record's "content_name" value
 * @method string        getContentText()   Returns the current record's "content_text" value
 * @method string        getContentImage()  Returns the current record's "content_image" value
 * @method integer       getCreatedBy()     Returns the current record's "created_by" value
 * @method integer       getUpdatedBy()     Returns the current record's "updated_by" value
 * @method CroAdminUsers getCroAdminUsers() Returns the current record's "CroAdminUsers" value
 * @method CroPages      getCroPages()      Returns the current record's "CroPages" value
 * @method CroCms        setPageUrlId()     Sets the current record's "page_url_id" value
 * @method CroCms        setContentName()   Sets the current record's "content_name" value
 * @method CroCms        setContentText()   Sets the current record's "content_text" value
 * @method CroCms        setContentImage()  Sets the current record's "content_image" value
 * @method CroCms        setCreatedBy()     Sets the current record's "created_by" value
 * @method CroCms        setUpdatedBy()     Sets the current record's "updated_by" value
 * @method CroCms        setCroAdminUsers() Sets the current record's "CroAdminUsers" value
 * @method CroCms        setCroPages()      Sets the current record's "CroPages" value
 * 
 * @package    courtreservationonline
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCroCms extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cro_cms');
        $this->hasColumn('page_url_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('content_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('content_text', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
        $this->hasColumn('content_image', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
        $this->hasColumn('created_by', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('updated_by', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CroAdminUsers', array(
             'local' => 'updated_by',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('CroPages', array(
             'local' => 'page_url_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}