<?php

/**
 * BaseCroCmsImages
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $location
 * @property string $content_name
 * @property string $content_image
 * 
 * @method string       getLocation()      Returns the current record's "location" value
 * @method string       getContentName()   Returns the current record's "content_name" value
 * @method string       getContentImage()  Returns the current record's "content_image" value
 * @method CroCmsImages setLocation()      Sets the current record's "location" value
 * @method CroCmsImages setContentName()   Sets the current record's "content_name" value
 * @method CroCmsImages setContentImage()  Sets the current record's "content_image" value
 * 
 * @package    courtreservationonline
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCroCmsImages extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cro_cms_images');
        $this->hasColumn('location', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('content_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('content_image', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}