<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/02/04 14:00:13
sfConfig::add(array(
  'app_base_url' => 'http://www.courtreservationonline.com',
  'app_passwordsalt' => 'cro',
  'app_remember_cookie_expiration' => 25920000,
  'app_remember_cookie_name' => 'remember_me',
));
