<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/02/04 05:00:13

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=doctorreservationonline',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
