<?php
// auto-generated by sfViewConfigHandler
// date: 2013/02/04 05:00:16
$response = $this->context->getResponse();

if ($this->actionName.$this->viewName == 'indexSuccess')
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}

if ($templateName.$this->viewName == 'indexSuccess')
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'Reservation Page', false, false);
  $response->addMeta('description', 'Court Reservation Online', false, false);
  $response->addMeta('keywords', 'court, reservation', false, false);
  $response->addMeta('language', 'en', false, false);
  $response->addMeta('robots', 'index, follow', false, false);

  $response->addStylesheet('reset.css', '', array ());
  $response->addStylesheet('global.css', '', array ());
  $response->addStylesheet('jquery.timepicker.css', '', array ());
  $response->addStylesheet('home-styles.css', '', array ());
  $response->addStylesheet('fullcalendar.css', '', array ());
  $response->addStylesheet('fullcalendar-modified.css', '', array ());
  $response->addJavascript('jquery-1.8.3.min.js', '', array ());
  $response->addJavascript('moment.min.js', '', array ());
  $response->addJavascript('jquery.timepicker.js', '', array ());
  $response->addJavascript('scripts.js', '', array ());
  $response->addJavascript('calendar/fullcalendar.min.js', '', array ());
  $response->addJavascript('calendar-script.js', '', array ());
}
else
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'Court Reservation Online', false, false);
  $response->addMeta('description', 'Court Reservation Online', false, false);
  $response->addMeta('keywords', 'court, reservation', false, false);
  $response->addMeta('language', 'en', false, false);
  $response->addMeta('robots', 'index, follow', false, false);

  $response->addStylesheet('reset.css', '', array ());
  $response->addStylesheet('global.css', '', array ());
  $response->addStylesheet('jquery.timepicker.css', '', array ());
  $response->addStylesheet('home-styles.css', '', array ());
  $response->addJavascript('jquery-1.8.3.min.js', '', array ());
  $response->addJavascript('moment.min.js', '', array ());
  $response->addJavascript('jquery.timepicker.js', '', array ());
  $response->addJavascript('scripts.js', '', array ());
}

