<?php

/**
 * CroAdminUsersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CroAdminUsersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CroAdminUsersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CroAdminUsers');
    }

   	public function getAdminUserByUsernameAndPassword($username, $password)
	{
        $record = Doctrine_Query::create()
					->from('CroAdminUsers u')
        			->where('u.username = ?', $username)
        			->andWhere('u.password = ?', md5(sfConfig::get('app_passwordsalt') . $password))
        			->fetchArray();
                    
        return $record[0];
	}
}