<?php

/**
 * CroCourtCloseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CroCourtCloseTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CroCourtCloseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CroCourtClose');
    }
}