<?php

/**
 * CroCmsImagesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CroCmsImagesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CroCmsImagesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CroCmsImages');
    }
}