<?php

/**
 * CroCourtsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CroCourtsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CroCourtsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CroCourts');
    }
}