<?php

/**
 * CroCmsTextsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CroCmsTextsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CroCmsTextsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CroCmsTexts');
    }
}