<?php

/**
 * CroGroupsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CroGroupsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CroGroupsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CroGroups');
    }
}