<?php

/**
 * CroPagesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CroPagesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CroPagesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CroPages');
    }
}