<?php

/**
 * CroPaymentsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CroPaymentsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CroPaymentsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CroPayments');
    }

    public function getPayment($courtid)
	{
        $timeAvailable = Doctrine_Query::create()->from('CroPayments u');

        if($courtid) $record = $timeAvailable->where('u.reservationid = ?', $courtid)->fetchArray();
        else $record = $timeAvailable->fetchArray();
        
        return $record;
	}
}