<?php

/**
 * CroReservationsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CroReservationsTable extends Doctrine_Table
{
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CroReservations');
    }

    public function getUserReservations($userid)
	{
        $reservation = Doctrine_Query::create()->from('CroReservations u');

        if($userid) $record = $reservation->where('u.userid = ?', $userid)->fetchArray();
        else $record = $reservation->fetchArray();
        
        return $record;
	}

    public function checkReservations($courtid, $date, $start, $end)
    {
        $reservation = Doctrine_Query::create()
                        ->from('CroReservations u')
                        ->where('u.courtid = ? AND u.start LIKE ?', array($courtid, $date . '%'))
                        ->fetchArray();

        $isAvailable = true;
        foreach($reservation as $key => $val){
            if((($val['start'] <= $start) && ($val['end'] > $start)) || (($val['start'] < $end) && ($val['end'] >= $end))){
                $isAvailable = false;
            }
        }

        return $isAvailable;
    }
}