<?php

/**
 * CroUsersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CroUsersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CroUsersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CroUsers');
    }

   	public function getUserByUsernameAndPassword($username, $password)
	{
        $record = Doctrine_Query::create()
					->from('CroUsers u')
        			->where('u.username = ?', $username)
        			->andWhere('u.password = ?', md5(sfConfig::get('app_passwordsalt') . $password))
        			->fetchArray();
                    
        return $record;
	}
}