<?php

/**
 * CroUsersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CroUsersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CroUsersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CroUsers');
    }

   	public function getUserByEmailAndPassword($email, $password)
	{
        $record = Doctrine_Query::create()
					->from('CroUsers u')
        			->where('u.email = ?', $email)
        			->andWhere('u.password = ?', md5(sfConfig::get('app_passwordsalt') . $password))
        			->fetchArray();

        return empty($record) ? NULL : $record[0];
	}

    public function getUserListByFilter($email)
    {
        $record = Doctrine_Query::create()
                    ->from('CroUsers u')
                    ->where('u.email LIKE ?', '%'. $email . '%')
                    ->fetchArray();

        return isSet($record[0]) ? $record : null;
    }

    public function getUserIdForFilter($email)
    {
        $record = Doctrine_Query::create()
                    ->from('CroUsers u')
                    ->where('u.email = ?', $email)
                    ->fetchArray();

        return isSet($record[0]) ? $record[0] : null;
    }
}