<?php

/**
 * CroUsersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CroUsersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CroUsersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CroUsers');
    }
}