indexSuccess:
  metas:
    title:        'Home Page'
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    []

  javascripts:    []