<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/11/20 07:20:59

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=courtreservationonline',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
