<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/01/24 06:06:27
sfConfig::add(array(
  'app_base_url' => 'http://www.courtreservationonline.com/admin.php',
  'app_passwordsalt' => 'cro',
  'app_number_users_display' => 20,
));
