<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/01/21 12:34:28

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=courtreservationonline',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
