CroAdminUsers:
  actAs: { Timestampable: ~ }
  columns:
    username: { type: string(255), notnull: true, unique: true }
    email: { type: string(255), notnull: true, unique: true }
    password: { type: string(32), notnull: true }
    fname: { type: string(255), notnull: true }
    lname: { type: string(255), notnull: true }
    address: { type: string(4000) }
    contact1: { type: string(255) }
    contact2: { type: string(255) }
    website: { type: string(255) }
    company_logo: { type: string(255) }
    lastlogin: { type: timestamp, notnull: true }
    status: { type: boolean, notnull: true, default: 0 }

CroUsers:
  actAs: { Timestampable: ~ }
  columns:
    username: { type: string(255), notnull: true, unique: true }
    password: { type: string(32), notnull: true }
    fname: { type: string(255), notnull: true }
    lname: { type: string(255), notnull: true }
    minitial: { type: string(255) }
    email: { type: string(255), notnull: true, unique: true }
    phone: { type: string(255) }
    user_type: { type: string(255), notnull: true }
    subscription_type: { type: string(255), notnull: true }
    status: { type: boolean, notnull: true, default: 0 }

CroCourts:
  actAs: { Timestampable: ~ }
  columns:
    name: { type: string(255), notnull: true }
    status: { type: boolean, notnull: true, default: 0}
    indoor: { type: boolean, notnull: true, default: 0}
    lights: { type: boolean, notnull: true, default: 0}
    priorreservationhours: { type: integer, notnull: true }
    maxreservationhours: { type: integer, notnull: true }
    rate: { type: double, notnull: true }
    start_time: { type: timestamp, notnull: true }
    end_time: { type: timestamp, notnull: true }
    created_by: { type: integer, notnull: true }
    updated_by: { type: integer, notnull: true }
  relations:
    CroAdminUsers: { local: created_by, foreign: id }
    CroAdminUsers: { local: updated_by, foreign: id }

CroReservations:
  actAs: { Timestampable: ~ }
  columns:
    userid: { type: integer, notnull: true }
    courtid: { type: integer, notnull: true }
    start_date: { type: date, notnull: true }
    end_date: { type: date, notnull: true }
    start_time: { type: timestamp, notnull: true }
    end_time: { type: timestamp, notnull: true }
    status: { type: boolean, notnull: true, default: 0 }
    payment_status: { type: string(255), notnull: true, default: 0 }
  relations:
    CroUsers: { local: userid, foreign: id }
    CroCourts: { local: courtid, foreign: id }

CroPayments:
  actAs: { Timestampable: ~ }
  columns:
    reservationid: { type: integer, notnull: true }
    rate: { type: double, notnull: true }
    payment_date: { type: date, notnull: true }
    payment_type: { type: string(255), notnull: true }
  relations:
    CroReservations: { onDelete: CASCADE, local: reservationid, foreign: id }